import numpy as np
a= np.array([1,3,5,7,9])
print(a)
a= np.arange(1,11)
print(a)
p= np.zeros((3,3))
print(p)
q=np.ones((2,2))
print(q)
r=np.full((2,2),4)
print(r)
s=np.eye(4)
print(s)
t=np.random.random((3,3))
print(t)
a = np.array([[5, 6], [7, 8]])
print(a[0,0])
print(type(a))


a=np.float64(21)
print(a)
a=np.int8(21.0)
print(a)
a=bool(21)
print(a)
a=bool(0)
print(a)
a=np.float64(True)
print(a)
a=np.int16(False)
print(a)
a=complex(42,1)
print(a)


#a=np.float64(42.0+1.j)
#print(a)
a=np.array([1,2,3,4,5],dtype=np.int8)
print(a.dtype.type)
print(a.dtype)
#print(dtype(a[0]))
a=np.array([1,2,3,4,5],dtype="float64")
print(a)
print(a.dtype.type)
print(a.dtype)
#print(dtype(a[0]))

dt= np.dtype('>i4')
print(dt.byteorder)
print(dt.itemsize)
print(dt.type)
print(dt.name)
print(dt)
print("reshape")
a=np.arange(12)
print(a.shape)
a2= a.reshape(4,3)
print(a2)
a3=a.reshape(3,4)
print(a3)
print(np.arange(1,10).reshape(3,3))
print(a.flatten())
print(a.ravel())
print(a2.transpose())
print(a.resize(4,3))

print("stacking")
a=np.arange(1,10).reshape(3,3)
print(a)
b=a*2
print(b)
c=np.hstack((a,b))
print(c)
d=np.concatenate((a,b),axis=1)
print(d)
c=np.vstack((a,b))
print(c)
d=np.concatenate((a,b),axis=0)
print(d)
g=np.dstack((a,b))
print(g)
a=np.arange(4,7)
print(a)
b=a*2
print(b)
cs=np.column_stack((a,b))
print(cs)
rs=np.row_stack((a,b))
print(rs)
a=np.arange(1,10).reshape(3,3)
print(a)
hor_split=np.hsplit(a,3)
print(hor_split)
vert_split= np.vsplit(a,3)
print(vert_split)
#depth_split=np.dsplit(a,3)
#print(depth_split)
a=np.arange(1,10).reshape(3,3)
print(a)
b=a.astype(np.float32)
print(b)
alist=a.tolist()
print(alist)
print("view and copy")
a=np.arange(1,5).reshape(2,2)
print("a old",a)
b=a
c=a.copy()
d=a.view()
a[1]=[99,89]
print("a new",a)
print("b",b)
print("c",c)
print("d",d)
print("a",a)

a=np.arange(0,10)
print(a)
b=a[3:6]
print(b)
print(a[-3:])
print(a[2:9:3])
a=np.arange(21,41,2)
print(a[a>30])
a=np.arange(1,21).reshape(5,4)
print(a[[1,2]])
row=np.array([1,2])
col=np.array([2,3])
print(a[row,col])
depth_split=np.dsplit(a,3)
print(depth_split)


                
